version: 2
build:
  os: 'ubuntu-lts-latest'
  tools:
    python: "python-latest"
    # You can also specify other tool versions:
    # nodejs: "16"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# # Dependencies required to build your docs
# python:
#    install:
#    - requirements: docs/requirements.txt
