version: 2
build:
  os: 'ubuntu-lts-latest'
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    # nodejs: "16"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py
   fail_on_warning: true

# Dependencies required to build your docs
python:
   install:
   - requirements: docs/requirements.txt
   # Install our python package before building the docs
   - method: pip
      path: .
