[tool.poetry]
name = "pybear"
version = "0.1.8"
description = "Python modules for miscellaneous data analytics applications"
license = "BSD-3-clause"
authors = ["Bill Sousa <WKSJR99@msn.com>"]
maintainers = ["Bill Sousa"]
readme = "README.rst"
# The contents of the README file(s) are used to populate the Description field of your distribution’s metadata (similar to 
# long_description in setuptools). When multiple files are specified they are concatenated with newlines.
homepage = "https://github.com/PylarBear/pybear"
repository = "https://github.com/PylarBear/pybear"
#documentation
keywords = ["data analytics numpy pandas sci-kit dask dask_ml"]
#classifiers
packages = [
	{ include = "pybear", from = "src"}
]
include = [
    "LICENSE",
    "README.rst",
    "CHANGELOG.md",
    "tests"
]
#exclude


[tool.poetry.dependencies]
# These packages are mandatory and form the core of this package’s distribution.
python = "^3.9, <3.14"
dask = "*"
dask-ml = "*"
distributed = "*"
joblib = "*"
numpy = ">=1.26.0"
pandas = "*"
scikit-learn = "*"
typing_extensions = "*"


[tool.poetry.group.dev.dependencies]
jupyter = "*"
notebook = "*"
pyarrow = "^17.0.0"
bokeh = "*"
graphviz = "*"
docutils = ">=0.20"
sphinx = "*"
sphinx-autobuild = "*"
sphinx-rtd-theme = "*"
polars-lts-cpu = "*"


[tool.poetry.group.test.dependencies]
pytest = "*"
lightgbm = "*"
xgboost = "*"
scipy = "*"
polars-lts-cpu = "*"


[tool.poetry.extras]
# Optional dependencies. They can be opted into by apps.


[tool.poetry.scripts]


[tool.poetry.plugins]


[tool.poetry.urls]
# If you publish your package on PyPI, they will appear in the Project Links section.


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

