[tool.poetry]
name = "pybear"
version = "0.1.0"
description = "Python modules for miscellaneous data analytics applications"
license = "Proprietary"
authors = ["Bill Sousa <WKSJR99@msn.com>"]
maintainers = []
readme = "README.rst"
# The contents of the README file(s) are used to populate the Description field of your distribution’s metadata (similar to 
# long_description in setuptools). When multiple files are specified they are concatenated with newlines.
homepage = "https://github.com/PylarBear/pybear"
repository = "https://github.com/PylarBear/pybear"
#documentation
keywords = ["analytics data science numpy sci-kit"]
#classifiers
#packages
#include
#exclude


[tool.poetry.dependencies]
# These packages are mandatory and form the core of this package’s distribution.
python = "^3.9"
dask = "<2024.3.0"
dask-ml = "*"
joblib = "*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
scipy = "*"


[tool.poetry.group.dev.dependencies]
distributed = "*"
jupyter = "*"
notebook = "*"


[tool.poetry.group.test.dependencies]
pytest = "*"
lightgbm = "*"
xgboost = "*"


[tool.poetry.group.docs.dependencies]


[tool.poetry.extras]
# Optional dependencies. They can be opted into by apps.


[tool.poetry.scripts]


[tool.poetry.plugins]


[tool.poetry.urls]
# If you publish your package on PyPI, they will appear in the Project Links section.


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"






