import numpy as np


def lexicon_z():
    return np.array([
                    "ZAG",
                    "ZAGGED",
                    "ZAGGING",
                    "ZAGS",
                    "ZAMBONI",
                    "ZAMBONIS",
                    "ZEAL",
                    "ZEALAND",
                    "ZEALANDS",
                    "ZEALOT",
                    "ZEALOTS",
                    "ZEALOUS",
                    "ZEBRA",
                    "ZEBRAS",
                    "ZEN",
                    "ZENITH",
                    "ZERO",
                    "ZEROED",
                    "ZEROES",
                    "ZEROS",
                    "ZIG",
                    "ZIGGED",
                    "ZIGGING",
                    "ZIGS",
                    "ZINGER",
                    "ZINGERS",
                    "ZIP",
                    "ZIPLINE",
                    "ZIPLINES",
                    "ZIPPED",
                    "ZIPPER",
                    "ZIPPERS",
                    "ZIPPING",
                    "ZIPPY",
                    "ZIPS",
                    "ZIRCONIUM",
                    "ZIT",
                    "ZITI",
                    "ZITS",
                    "ZODIAC",
                    "ZOMBIE",
                    "ZOMBIES",
                    "ZONE",
                    "ZONED",
                    "ZONES",
                    "ZONING",
                    "ZOO",
                    "ZOOLOGIST",
                    "ZOOLOGISTS",
                    "ZOOLOGY",
                    "ZOOM",
                    "ZOOMED",
                    "ZOOMING",
                    "ZOOMS",
                    "ZOOS",
                    "ZULU",
                    "ZYGOTE",
                    "ZYGOTES"
    ], dtype='<U30')





