# Author:
#         Bill Sousa
#
# License: BSD 3 clause
#



X = [
        ["ACTIVITY", "APPRECIATE", "ANIMAL", "ANTICIPATE", "BEAUTIFUL", "BENEATH", "BENEFIT", "BRINGING", "BRIGHT", "CAREFUL"],
        ["CARING", "CATCHING", "CELEBRATE", "CIRCUMSTANCE", "COHESION", "COMMON", "CREATIVITY", "CURIOUS", "DANGER", "DARING"],
        ["DESTINY", "DESIRE", "DIVINE", "DREAMING", "EDUCATE", "ELITE", "ENCOURAGE", "EXCITEMENT", "EXPECT", "FAITHFUL"],
        ["FANTASTIC", "FAVORITE", "FRIEND", "FRIENDLY", "FUTURE", "GATHERING", "GENEROUS", "GENERATE", "GLORIOUS", "HARMONY"],
        ["HELPFUL", "HOPEFUL", "HONESTY", "HUMANITY", "INFLUENCE", "INSIGHT", "INTEREST", "INTELLIGENT", "JOYFUL", "JUDGEMENT"],
        ["KINDNESS", "KNOWLEDGE", "LEADER", "LEARNING", "LIBERATE", "LIFE", "LIGHT", "LOVE", "MAGNIFICENT", "MEANING"],
        ["MEMORIES", "MIND", "MOTIVATION", "NATIONAL", "NATURE", "OPTIMISTIC", "ORDERLY", "OPPORTUNITY", "PATIENCE", "PASSION"],
        ["PEACEFUL", "PERFECT", "PERSISTENT", "PLEASURE", "POSITIVE", "POWERFUL", "PROGRESS", "PURPOSE", "QUALITY", "QUEST"],
        ["REACHING", "REALITY", "RESPECTFUL", "SINCERE", "SKILLFUL", "SPIRITUAL", "STRATEGY", "SUCCESS", "SUPPORT", "TALENT"],
        ["THOUGHTFUL", "TREMENDOUS", "UNITY", "USEFUL", "VISION", "WEALTH", "WISDOM", "WORTHY", "ZEAL", "ZESTFUL"],
        ["ABUNDANT", "ADVENTURE", "AMBITION", "ANCIENT", "ARTIST", "AWAKEN", "BELIEVE", "BLESSING", "CALM", "CAREER"],
        ["CHALLENGE", "CHARACTER", "CLARITY", "COMMIT", "COURAGE", "CREATIVE", "CURRENT", "DELIGHT", "DESTROY", "DISCOVER"],
        ["DREAMER", "ELATION", "EMPATHY", "ENERGY", "ENDEAVOR", "ENGAGE", "ENLIGHTEN", "EXPLORER", "FOCUS", "FOREVER"],
        ["FRIENDS", "GAIN", "GREATNESS", "HEROIC", "HOPE", "HORIZON", "IDEAL", "IGNITE", "INSPIRE", "JOY"],
        ["JOURNEY", "JUSTICE", "LEGACY", "LIFELESS", "LOVEABLE", "MASTER", "MYSTIC", "NOBLE", "OBSERVE", "PEACE"],
        ["PERSIST", "PLEASANT", "PROSPER", "REFLECT", "RELIABLE", "REMARKABLE", "RESOURCEFUL", "RESTORE", "SHARE", "SIMPLIFY"],
        ["SKILLED", "SOAR", "STRENGTH", "SUBLIME", "TRIUMPH", "UNITY", "VISIONARY", "WEALTHY", "WISDOM", "YOUTHFUL"],
        ["ZENITH", "AMAZIN", "BEAUTIFULL", "CREATING", "DILIGENCE", "EXPECTATION", "EXCITING", "FLEXABILITY", "FREEDOM", "GLOURY"],
        ["HARMONIOUS", "HEROISM", "INFLUENCER", "INSPIRATION", "MINDFUL", "PERSISTACE", "PROGRESSIVE", "TRULY", "VALUEABLE", "VICTORY"]
]


