# Author:
#         Bill Sousa
#
# License: BSD 3 clause
#


# pizza, this is placeholder copied from dask_ml 24_06_17_08_42_00
# anticipating this will be overwritten by setuptools_scm or poetry?


# file generated by setuptools_scm
# don't change, don't track in version control


try:
    from importlib.metadata import version as get_version
except ImportError:
    # For older Python versions, use importlib-metadata package
    from importlib_metadata import version as get_version



TYPE_CHECKING = True   # pizza, revised from dask_ml
if TYPE_CHECKING:
    from typing import Tuple, Union
    VERSION_TUPLE = Tuple[Union[int, str], ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = get_version('pybear')   # pizza, revised from dask_ml
__version_tuple__ = version_tuple = (0, 1)   # pizza, revised from dask_ml




