import numpy as np


def lexicon_y():
    return np.array([
                    "YA",
                    "YAHOO",
                    "YAHOOS",
                    "YALE",
                    "YANKED",
                    "YANKEE",
                    "YANKEES",
                    "YANKER",
                    "YANKERS",
                    "YANKING",
                    "YANKS",
                    "YARD",
                    "YARDS",
                    "YARN",
                    "YARNS",
                    "YAWN",
                    "YAWNED",
                    "YAWNING",
                    "YAWNS",
                    "YE",
                    "YEAH",
                    "YEAR",
                    "YEAREND",
                    "YEARLONG",
                    "YEARLY",
                    "YEARN",
                    "YEARNED",
                    "YEARNING",
                    "YEARNS",
                    "YEARS",
                    "YEAST",
                    "YEASTS",
                    "YELL",
                    "YELLED",
                    "YELLER",
                    "YELLERS",
                    "YELLING",
                    "YELLOW",
                    "YELLOWED",
                    "YELLOWING",
                    "YELLOWISH",
                    "YELLOWNESS",
                    "YELLOWSTONE",
                    "YELLS",
                    "YEMEN",
                    "YEMENI",
                    "YEN",
                    "YES",
                    "YESTER",
                    "YESTERDAY",
                    "YESTERDAYS",
                    "YET",
                    "YETI",
                    "YETIS",
                    "YEW",
                    "YEWS",
                    "YIELD",
                    "YIELDED",
                    "YIELDING",
                    "YIELDS",
                    "YOKE",
                    "YOKED",
                    "YOKES",
                    "YOKING",
                    "YON",
                    "YONDER",
                    "YONKERS",
                    "YORE",
                    "YORK",
                    "YORKIE",
                    "YORKIES",
                    "YORKS",
                    "YOU",
                    "YOUD",
                    "YOULL",
                    "YOUNG",
                    "YOUNGER",
                    "YOUNGEST",
                    "YOUR",
                    "YOURE",
                    "YOURS",
                    "YOURSELF",
                    "YOURSELVES",
                    "YOUTH",
                    "YOUTHFUL",
                    "YOUTHS",
                    "YOUTUBE",
                    "YOUVE",
                    "YUAN",
                    "YUCATAN",
                    "YUGOSLAV",
                    "YUGOSLAVIA",
                    "YUGOSLAVIAN",
                    "YUKON",
                    "YUMA"
    ], dtype='<U30')





