name: Matrix Testing

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies with Poetry
      run: |
        poetry lock
        poetry install

    - name: Install LLVM (macOS only)
      if: matrix.os == 'macos-latest'
      run: |
        brew install llvm
        echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH
        echo "/usr/local/opt/llvm/lib" >> $GITHUB_LD_LIBRARY_PATH
    
    - name: Install LLVM (Ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm

    - name: Run tests
      run: |
        poetry run pytest 



