name: py3.13 Matrix Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.13']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # Conditional step to install libomp on macOS
    # Need libomp on macOS to run XGBoost
    - name: Install libomp on macOS
      if: matrix.os == 'macos-latest'
      run: brew install libomp

    # Need llvm on macOS to run py3.13
    # - name: Install llvm on macOS
    #   if: matrix.os == 'macos-latest'
    #   run: brew install llvm

    # Need to explicitly set the PATH to include LLVM’s binary directory
    # - name: Configure LLVM PATH on macOS
    #   if: matrix.os == 'macos-latest'
    #   run: echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> $GITHUB_ENV

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies with Poetry
      run: |
        poetry lock
        poetry add llvmlite --lock --dev
        poetry install

    - name: Run tests
      run: poetry run pytest tests/ --doctest-modules -v
      timeout-minutes: 120
