# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: GitHub Packages Publishing Workflow

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

  workflow_dispatch:
  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ^3.9  # Replace 'x' with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install pip poetry setuptools twine wheel
          # pip install -r requirements.txt
          poetry lock
          poetry install

      - name: Build and Publish
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
