# This workflow will upload a Python Package using poetry when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: GitHub Packages Publishing Workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:
  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: ^3.9

      - name: Install dependencies
        run: |
          python -m pip install pip poetry --upgrade pip # setuptools twine wheel
          # pip install -r requirements.txt
          poetry lock
          poetry install

      - name: Build and Publish
        run: |
          poetry build
          poetry publish -r testpypi
          # python setup.py sdist bdist_wheel
          # twine upload dist/*
        env:
          POETRY_HTTP_BASIC_GITHUB_USERNAME: __token__
          POETRY_HTTP_BASIC_GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
